# Generated by Django 5.0.4 on 2024-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_org_shifts'),
        ('login', '0007_user_is_clocked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='shifts_worked_by_user', to='core.shift'),
        ),
    ]
