# Generated by Django 5.0.4 on 2024-08-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_user_shifts_user_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shifts',
        ),
    ]
