# Generated by Django 5.0.4 on 2024-08-11 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=30, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reg_hr', models.IntegerField()),
                ('night_diff', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('total_hours', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
