# Generated by Django 5.0.4 on 2024-08-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shift_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orgs',
            new_name='Org',
        ),
    ]
