# Generated by Django 5.0.4 on 2024-08-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_orgs_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='shifts',
        ),
    ]
