# Generated by Django 5.0.4 on 2024-08-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_org_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='shifts_worked', to='core.shift'),
        ),
    ]
