# Generated by Django 5.0.4 on 2024-08-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_org_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='shifts',
        ),
    ]
