name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: docker-compose up -d
    
